
/*CRIANDO O BANCO*/
CREATE DATABASE OFICINA;

USE OFICINA;

/* CRIANDO AS TABELAS*/
CREATE TABLE CLIENTE(
	ID_CLIENTE INT PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(30) NOT NULL,
	SEXO CHAR(1) NOT NULL,
	CPF VARCHAR(15) UNIQUE NOT NULL,
	EMAIL VARCHAR(20)
);

CREATE TABLE ENDERECO (
	ID_ENDERECO INT PRIMARY KEY AUTO_INCREMENT,
	ESTADO CHAR(2),
	CIDADE VARCHAR(30),
	BAIRRO VARCHAR(30),
	RUA VARCHAR(30),
	NUM INT(6),
	ID_CLIENTE_END INT,
	FOREIGN KEY(ID_CLIENTE_END)
	REFERENCES CLIENTE(ID_CLIENTE)
);

CREATE TABLE TELEFONE(
	ID_TEL INT PRIMARY KEY AUTO_INCREMENT,
	TIPO VARCHAR(5),
	TELEFONE VARCHAR(15),
	ID_CLIENTE_TEL INT,
	FOREIGN KEY(ID_CLIENTE_TEL)
	REFERENCES CLIENTE (ID_CLIENTE)
);

CREATE TABLE CARRO(
	ID_CARRO INT PRIMARY KEY AUTO_INCREMENT,
	MARCA VARCHAR(30),
	COR VARCHAR(30),
	PLACA VARCHAR(10),
	ID_CLIENTE_CARRO INT,
	FOREIGN KEY(ID_CLIENTE_CARRO)
	REFERENCES CLIENTE(ID_CLIENTE)
);